services:
  backend:
    container_name: yt-dwnlder
    build:
      context: ./backend
    image: yt-dwnlder-backend
    user: 1000:100
    ports:
      - "8099:8099"

    environment:
      DOWNLOAD_DIR: /downloads
      COOKIES_PATH: /cookies/cookies.txt

    volumes:
      - ./downloads:/downloads
      - ./cookies:/cookies

    restart: unless-stopped
